version: '3.8'

services:
  archangel:
    build: .
    container_name: archangel-ai-system
    privileged: true  # Required for kernel module operations
    volumes:
      # Mount the project directory for development
      - .:/app
      # Persist Hugging Face cache
      - archangel-hf-cache:/app/.cache/huggingface
      # Persist logs
      - archangel-logs:/app/logs
      # Mount host's /proc for system monitoring (optional)
      - /proc:/host/proc:ro
    environment:
      # Set your Hugging Face token here or via .env file
      - HF_TOKEN=${HF_TOKEN:-}
      - HUGGINGFACE_TOKEN=${HF_TOKEN:-}
      # Development settings
      - PYTHONPATH=/app
      - PATH=/app/venv/bin:$PATH
    ports:
      # Expose ports for potential web interfaces
      - "8000:8000"  # Main web interface
      - "8888:8888"  # Jupyter notebook (if added)
    networks:
      - archangel-network
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Optional: Database for storing analysis results
  archangel-db:
    image: postgres:15-alpine
    container_name: archangel-database
    environment:
      - POSTGRES_DB=archangel
      - POSTGRES_USER=archangel
      - POSTGRES_PASSWORD=archangel_secure_password
    volumes:
      - archangel-db-data:/var/lib/postgresql/data
    networks:
      - archangel-network
    restart: unless-stopped
    profiles:
      - with-db  # Only start with docker-compose --profile with-db up

  # Optional: Redis for caching and session management
  archangel-cache:
    image: redis:7-alpine
    container_name: archangel-cache
    volumes:
      - archangel-redis-data:/data
    networks:
      - archangel-network
    restart: unless-stopped
    profiles:
      - with-cache  # Only start with docker-compose --profile with-cache up

volumes:
  archangel-hf-cache:
    driver: local
  archangel-logs:
    driver: local
  archangel-db-data:
    driver: local
  archangel-redis-data:
    driver: local

networks:
  archangel-network:
    driver: bridge