# Basic Suricata configuration for blue team monitoring
default-log-dir: /var/log/suricata/

stats:
  enabled: yes
  interval: 8

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      
af-packet:
  - interface: eth0
    threads: 1
    defrag: yes
    
detect-engine:
  - profile: medium
  - custom-values:
      toclient-groups: 200
      toserver-groups: 200